### ISSUE TITLE
Gdal::Ogr.open returns Nil

### ISSUE THREAD

**Issue by itsravenous** [zhm/gdal-ruby#10]
test.rb:
```ruby
require 'gdal-ruby/ogr'

ds = Gdal::Ogr.open('./test.tif')
puts ds.nil?
```

```
$ ruby test.rb
True
```

`test.tif` is a GeoTIFF. We've successfully read `test.tif` with the [node](https://www.npmjs.com/package/gdal) and [python](https://pypi.python.org/pypi/GDAL/) GDAL bindings, but would really like to use the ruby bindings in this instance.

The snippet from the README works, so GDAL appears to be loading ok.

```
$ ruby -e "require 'gdal-ruby/ogr'; puts Gdal::Ogr.create_geometry_from_wkt('POINT (30 10)').export_to_json"

{ "type": "Point", "coordinates": [ 30.0, 10.0 ] }
```

**Comment by zhm** [comment]
Sorry for the WAY delayed response, but I think you need to use the `gdal` module, not the `ogr` module:

```ruby
require 'gdal-ruby/gdal'

ds = Gdal::Gdal.open('./test.tif')
puts ds.nil?
```
