### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by johnjohndoe** [zhm/gdal-ruby#6]
It would be helpful if you could maintain a dedicated changelog which **summarizes the changes** which happened from release to release. You can either use the GitHub releases (which only works here) or just add a `CHANGELOG.md` [like other repositories do](https://github.com/johnjohndoe/Umweltzone/blob/master/CHANGELOG.md).

**Comment by zhm** [comment]
I've added a changelog file.

**Comment by johnjohndoe** [comment]
If you could **add the notes for the former releases** (there are some missing: v0.0.2, v0.0.4, v0.0.5) too, that would be perfect.
