### ISSUE TITLE
Raster support

### ISSUE THREAD

**Issue by migtorres** [zhm/gdal-ruby#8]
Hi!

Thanks for the great job. I can't open raster files (tiff. Using Gdal::Ogr.open('file.tif) I got a nil value. 

Does this gem support that? 

Thanks

**Comment by aleksejleonov** [comment]
Hi

`Gdal::Ogr` is only for vector files with geometries inside (ESRI shapefiles, geojson, etc.).
`Gdal::Gdal` is only for raster files (GeoTIFF, HDF, etc.).

You should use `Gdal::Gdal` namespace to work with raster files.

**Comment by migtorres** [comment]
Great!

Thanks!
